In [1]:
import pandas as pd
import numpy as np

In [2]:
users=pd.read_csv("users.csv")

In [5]:
users.head()

   user_id signup_date country device_type age_group acquisition_channel
0  U000001  2026-02-21     USA     Desktop     45-54         Paid Search
1  U000002  2026-01-15  Canada      Mobile       55+         Paid Search
2  U000003  2026-03-13   India      Mobile     25-34             Organic
3  U000004  2026-03-02     USA      Mobile     45-54              Social
4  U000005  2026-01-21      UK     Desktop     18-24             Organic

In [7]:
users.shape

(100100, 6)

In [8]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   user_id              100100 non-null  object
 1   signup_date          100100 non-null  object
 2   country              99898 non-null   object
 3   device_type          100000 non-null  object
 4   age_group            100100 non-null  object
 5   acquisition_channel  100100 non-null  object
dtypes: object(6)
memory usage: 4.6+ MB

In [11]:
users.describe(include='all')

        user_id signup_date country device_type age_group acquisition_channel
count    100100      100100   99898      100000    100100              100100
unique   100000          90       6           3         5                   5
top     U018773  2026-03-28   India      Mobile     25-34             Organic
freq          2        1184   34912       61855     36045               31912

In [18]:
users.isnull().sum()

user_id                  0
signup_date              0
country                202
device_type            100
age_group                0
acquisition_channel      0
dtype: int64

In [20]:
users.duplicated().sum()

100

In [21]:
users['user_id'].duplicated().sum()

100

In [22]:
users['user_id'].nunique()

100000

In [23]:
users['country'].value_counts(dropna=False)

country
India        34912
USA          24994
UK           11906
Canada       10004
Germany       9957
Australia     8125
NaN            202
Name: count, dtype: int64

In [24]:
users['device_type'].value_counts(dropna=False)

device_type
Mobile     61855
Desktop    30025
Tablet      8120
NaN          100
Name: count, dtype: int64

In [25]:
users['age_group'].value_counts(dropna=False)

age_group
25-34    36045
35-44    23147
18-24    19951
45-54    14003
55+       6954
Name: count, dtype: int64

In [26]:
users['acquisition_channel'].value_counts(dropna=False)

acquisition_channel
Organic        31912
Paid Search    24121
Social         18079
Referral       16018
Email           9970
Name: count, dtype: int64

In [27]:
users['signup_date'].min()

'2026-01-01'

In [28]:
users['signup_date'].max()

'2026-03-31'

In [29]:
users['signup_date'].isna().sum()

0

In [30]:
duplicate_users = users[
    users['user_id'].duplicated(keep=False)
].sort_values('user_id')

duplicate_users.head(10)

,user_id,signup_date,country,device_type,age_group,acquisition_channel
235,U000236,2026-01-20,India,Desktop,45-54,Paid Search
100062,U000236,2026-01-20,India,Desktop,45-54,Paid Search
1116,U001117,2026-01-23,Australia,Mobile,25-34,Organic
100043,U001117,2026-01-23,Australia,Mobile,25-34,Organic
1937,U001938,2026-02-16,India,Mobile,55+,Social
100065,U001938,2026-02-16,India,Mobile,55+,Social
2088,U002089,2026-03-19,India,Desktop,18-24,Paid Search
100083,U002089,2026-03-19,India,Desktop,18-24,Paid Search
100097,U002293,2026-01-12,USA,Desktop,35-44,Referral
2292,U002293,2026-01-12,USA,Desktop,35-44,Referral

In [31]:
duplicate_users

,user_id,signup_date,country,device_type,age_group,acquisition_channel
235,U000236,2026-01-20,India,Desktop,45-54,Paid Search
100062,U000236,2026-01-20,India,Desktop,45-54,Paid Search
1116,U001117,2026-01-23,Australia,Mobile,25-34,Organic
100043,U001117,2026-01-23,Australia,Mobile,25-34,Organic
1937,U001938,2026-02-16,India,Mobile,55+,Social
...,...,...,...,...,...,...
100022,U097962,2026-02-20,Australia,Mobile,25-34,Paid Search
98803,U098804,2026-03-14,India,Desktop,35-44,Email
100020,U098804,2026-03-14,India,Desktop,35-44,Email
100026,U099717,2026-03-05,India,Desktop,25-34,Organic
99716,U099717,2026-03-05,India,Desktop,25-34,Organic

In [32]:
experiments=pd.read_csv("experiments.csv")

In [35]:
experiments.head()

   user_id experiment_name experiment_group assignment_date variant_version
0  U000001   onboarding_v2        Treatment      2026-02-21              v2
1  U000002   onboarding_v2        Treatment      2026-01-15              v2
2  U000003   onboarding_v2        Treatment      2026-03-13              v2
3  U000004   onboarding_v2          Control      2026-03-02              v1
4  U000005   onboarding_v2          Control      2026-01-21              v1

In [36]:
experiments.shape

(100000, 5)

In [38]:
experiments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   user_id           100000 non-null  object
 1   experiment_name   100000 non-null  object
 2   experiment_group  100000 non-null  object
 3   assignment_date   100000 non-null  object
 4   variant_version   100000 non-null  object
dtypes: object(5)
memory usage: 3.8+ MB

In [42]:
experiments.describe(include='all')

,user_id,experiment_name,experiment_group,assignment_date,variant_version
count,100000,100000,100000,100000,100000
unique,100000,1,2,92,2
top,U000001,onboarding_v2,Treatment,2026-03-28,v2
freq,1,100000,50014,1187,50014

In [44]:
experiments.duplicated().sum()

0

In [45]:
experiments.isnull().sum()

user_id             0
experiment_name     0
experiment_group    0
assignment_date     0
variant_version     0
dtype: int64

In [48]:
experiments['user_id'].duplicated().sum()

0

In [49]:
experiments['experiment_group'].value_counts(dropna=False)

experiment_group
Treatment    50014
Control      49986
Name: count, dtype: int64

In [50]:
experiments['experiment_name'].value_counts(dropna=False)

experiment_name
onboarding_v2    100000
Name: count, dtype: int64

In [51]:
experiments['variant_version'].value_counts(dropna=False)

variant_version
v2    50014
v1    49986
Name: count, dtype: int64

In [52]:
experiments['assignment_date'] = pd.to_datetime(experiments['assignment_date'])
users['signup_date'] = pd.to_datetime(users['signup_date'])

check = experiments.merge(
    users[['user_id', 'signup_date']],
    on='user_id',
    how='left'
)

(check['assignment_date'] < check['signup_date']).sum()

50

In [53]:
pd.crosstab(
    experiments['experiment_group'],
    experiments['variant_version']
)

variant_version      v1     v2
experiment_group
Control           49986      0
Treatment             0  50014

In [54]:
invalid_assignments = check[
    check['assignment_date'] < check['signup_date']
].sort_values('assignment_date')

invalid_assignments.head(10)

,user_id,experiment_name,experiment_group,assignment_date,variant_version,signup_date
5094,U005090,onboarding_v2,Control,2025-12-20,v1,2026-01-06
59050,U058997,onboarding_v2,Treatment,2025-12-20,v2,2026-01-11
60801,U060744,onboarding_v2,Treatment,2025-12-20,v2,2026-03-14
63919,U063858,onboarding_v2,Control,2025-12-20,v1,2026-03-05
66867,U066801,onboarding_v2,Control,2025-12-20,v1,2026-03-03
73016,U072946,onboarding_v2,Treatment,2025-12-20,v2,2026-02-01
75665,U075593,onboarding_v2,Treatment,2025-12-20,v2,2026-03-12
77087,U077015,onboarding_v2,Control,2025-12-20,v1,2026-03-31
77220,U077147,onboarding_v2,Treatment,2025-12-20,v2,2026-03-03
79035,U078961,onboarding_v2,Control,2025-12-20,v1,2026-03-05

In [55]:
invalid_assignments[
    ['user_id', 'signup_date', 'assignment_date',
     'experiment_group', 'variant_version']
]

       user_id signup_date assignment_date experiment_group variant_version
5094   U005090  2026-01-06      2025-12-20          Control              v1
59050  U058997  2026-01-11      2025-12-20        Treatment              v2
60801  U060744  2026-03-14      2025-12-20        Treatment              v2
63919  U063858  2026-03-05      2025-12-20          Control              v1
66867  U066801  2026-03-03      2025-12-20          Control              v1
73016  U072946  2026-02-01      2025-12-20        Treatment              v2
75665  U075593  2026-03-12      2025-12-20        Treatment              v2
77087  U077015  2026-03-31      2025-12-20          Control              v1
77220  U077147  2026-03-03      2025-12-20        Treatment              v2
79035  U078961  2026-03-05      2025-12-20          Control              v1
80222  U080146  2026-01-18      2025-12-20          Control              v1
81432  U081356  2026-01-27      2025-12-20          Control              v1
84669  U084592  2026-01-13      2025-12-20          Control              v1
86451  U086371  2026-03-12      2025-12-20        Treatment              v2
86707  U086627  2026-01-22      2025-12-20          Control              v1
87647  U087567  2026-01-13      2025-12-20        Treatment              v2
88381  U088300  2026-03-30      2025-12-20          Control              v1
90356  U090272  2026-03-07      2025-12-20        Treatment              v2
92639  U092551  2026-02-15      2025-12-20          Control              v1
93870  U093781  2026-03-07      2025-12-20        Treatment              v2
94896  U094804  2026-01-08      2025-12-20        Treatment              v2
96996  U096902  2026-01-23      2025-12-20        Treatment              v2
55797  U055748  2026-01-24      2025-12-20        Treatment              v2
52852  U052806  2026-03-20      2025-12-20        Treatment              v2
51841  U051795  2026-01-03      2025-12-20        Treatment              v2
49994  U049951  2026-03-02      2025-12-20          Control              v1
5164   U005160  2026-01-30      2025-12-20        Treatment              v2
9240   U009230  2026-02-22      2025-12-20          Control              v1
10233  U010222  2026-01-24      2025-12-20          Control              v1
11818  U011805  2026-03-15      2025-12-20          Control              v1
13942  U013925  2026-02-16      2025-12-20        Treatment              v2
16859  U016840  2026-03-16      2025-12-20          Control              v1
20358  U020336  2026-02-06      2025-12-20          Control              v1
20453  U020431  2026-03-19      2025-12-20          Control              v1
21353  U021330  2026-02-22      2025-12-20          Control              v1
22881  U022857  2026-01-08      2025-12-20        Treatment              v2
97331  U097236  2026-01-31      2025-12-20        Treatment              v2
24097  U024072  2026-01-03      2025-12-20          Control              v1
25083  U025057  2026-01-10      2025-12-20          Control              v1
26452  U026426  2026-03-06      2025-12-20        Treatment              v2
27881  U027854  2026-03-27      2025-12-20        Treatment              v2
33566  U033533  2026-03-27      2025-12-20        Treatment              v2
33984  U033950  2026-02-11      2025-12-20        Treatment              v2
42551  U042513  2026-02-19      2025-12-20          Control              v1
47017  U046977  2026-02-14      2025-12-20        Treatment              v2
48458  U048416  2026-01-03      2025-12-20        Treatment              v2
49077  U049034  2026-02-09      2025-12-20        Treatment              v2
49892  U049849  2026-03-09      2025-12-20          Control              v1
25015  U024989  2026-01-18      2025-12-20        Treatment              v2
97893  U097798  2026-03-05      2025-12-20        Treatment              v2

In [56]:
invalid_assignments['days_before_signup'] = (
    invalid_assignments['signup_date']
    - invalid_assignments['assignment_date']
).dt.days

invalid_assignments['days_before_signup'].value_counts().sort_index()

days_before_signup
14     3
17     1
19     2
21     1
22     1
24     2
29     2
33     1
34     1
35     2
38     1
41     1
42     1
43     1
48     1
51     1
53     1
56     1
57     1
58     1
61     1
64     2
72     1
73     2
75     3
76     1
77     2
79     1
82     2
84     1
85     1
86     1
89     1
90     1
97     2
100    1
101    1
Name: count, dtype: int64

In [57]:
pd.crosstab(
    users['country'],
    experiments['experiment_group'],
    normalize='columns'
)

experiment_group   Control  Treatment
country
Australia         0.080650   0.081894
Canada            0.100016   0.100284
Germany           0.098813   0.100605
India             0.348703   0.350174
UK                0.120344   0.118074
USA               0.251473   0.248968

In [58]:
pd.crosstab(
    users['device_type'],
    experiments['experiment_group'],
    normalize='columns'
)

experiment_group   Control  Treatment
device_type
Desktop           0.299555   0.300925
Mobile            0.619738   0.617380
Tablet            0.080707   0.081696